name: Workflow B - CD

on:
  workflow_run:
    workflows: ["Workflow A - CI"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Step
        run: echo "🚀 CD triggered automatically after CI success"
