name: Workflow A - CI

on:
  workflow_dispatch:  # allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run Build
        run: echo "✅ CI build completed successfully"